import assert from 'node:assert/strict';
import { getEmployeeGeofenceRule, saveEmployeeGeofenceRule, saveGeofenceGroup, getGeofenceGroups, getResolvedGeofence } from './geofenceStore.js';
const data = new Map();
globalThis.localStorage = { getItem: (key) => data.get(key) ?? null, setItem: (key, value) => data.set(key, value) };
assert.deepEqual(getGeofenceGroups(), []);
assert.equal(getEmployeeGeofenceRule('TYS-1021').status, 'Not configured');
assert.equal(getEmployeeGeofenceRule('TYS-1008').group_id, '');
assert.equal(getEmployeeGeofenceRule('new').custom_latitude, '');
assert.equal(getResolvedGeofence('new'), null);
const rule = { ...getEmployeeGeofenceRule('test'), mode: 'custom', custom_latitude: 0, custom_longitude: 0, allow_wfh: true, status: 'Paused', notes: 'Temporary remote assignment' };
saveEmployeeGeofenceRule('test', rule);
const saved = getEmployeeGeofenceRule('test');
for (const key of Object.keys(rule)) assert.deepEqual(saved[key], rule[key]);
assert.ok(saved.updated_at);
const site = { group_id: 'test-site', name: 'User campus', latitude: 0, longitude: 0, radius_meters: 200 };
saveGeofenceGroup(site);
saveGeofenceGroup({ ...site, name: 'Updated campus' });
assert.equal(getGeofenceGroups().filter((group) => group.group_id === site.group_id).length, 1);
assert.equal(getGeofenceGroups()[0].name, 'Updated campus');
const legacy = { group_id: 'group-remote', name: 'Remote / Field Flexible Work', type: 'Unrestricted Location', latitude: 0, longitude: 0, radius_meters: 0, photo_required: false, is_unrestricted: true, address: 'Global Work-From-Anywhere Approved', assigned_departments: ['Field Consultants', 'Executive Board'] };
localStorage.setItem('pulse_geofence_groups', JSON.stringify([legacy, { ...legacy, name: 'My edited remote policy' }, site]));
assert.deepEqual(getGeofenceGroups().map(group => group.name), ['My edited remote policy', 'User campus']);
saveEmployeeGeofenceRule('missing-site', { mode: 'group', group_id: 'missing', status: 'Enforced' });
assert.equal(getResolvedGeofence('missing-site'), null);
localStorage.setItem = () => { throw new Error('Storage unavailable'); };
assert.throws(() => saveEmployeeGeofenceRule('test', rule), /Storage unavailable/);
assert.throws(() => saveGeofenceGroup(site), /Storage unavailable/);
console.log('Geofence persistence checks passed.');
