import { workflowApi } from './workflowApi';
let notifications = [];
let connected = false;
let timer = null;
let inFlight = false;
let sessionToken = null;
const listeners = new Set();
const token = () => localStorage.getItem('pulse_hrms_token');
const notify = () => listeners.forEach(listener => listener(notifications,connected));
async function refresh() {
  const current = token();
  if (sessionToken !== current) { sessionToken = current; notifications = []; connected = false; notify(); }
  if (!current || inFlight) return;
  inFlight = true;
  try {
    const result = await workflowApi.notifications();
    if (current !== token()) return;
    notifications = result; connected = true; notify();
  } catch {
    if (current === token()) { connected = false; notify(); }
  } finally { inFlight = false; }
}
export function connectRealtimeNotifications() { refresh(); }
export function subscribeNotifications(callback) {
  if (sessionToken !== token()) { sessionToken = token(); notifications = []; connected = false; }
  listeners.add(callback); callback(notifications,connected); refresh();
  if (!timer) timer = setInterval(refresh,15000);
  return () => { listeners.delete(callback); if (!listeners.size) { clearInterval(timer); timer = null; notifications = []; connected = false; } };
}
export async function markNotificationRead(id) { await workflowApi.read(id); await refresh(); }
export async function markAllNotificationsRead() { await workflowApi.read(); await refresh(); }
export async function approveNotificationAction(id) {
  const notification = notifications.find(item => item.id === id);
  if (!notification?.canApprove || !notification.requestId) throw new Error('You are not the assigned approver for this request.');
  const result = await workflowApi.decide(notification.requestId,'Approved','');
  await refresh(); return result;
}
// Request notifications are generated by the authenticated workflow service only.
export async function dispatchRealtimeNotification() { throw new Error('Submit a workflow request to notify its assigned recipients.'); }
