import React, { useState } from 'react';
import { Plus, Trash2, ArrowRight, AlertCircle, ShieldCheck } from 'lucide-react';
import { REQUEST_TYPES, defaultPolicy, defaultResponsibilities, resolveRoute } from '../../../shared/workflowModel.mjs';
import './WorkflowSettings.scss';
const labels = { leave: 'Leave', attendance: 'Attendance corrections', expense: 'Expenses', other: 'Other requests' };
export function WorkflowSettings({ configuration, onChange, people, view }) {
  const [kind, setKind] = useState('leave');
  const [search, setSearch] = useState('');
  const [requester, setRequester] = useState('');
  const [days, setDays] = useState(1);
  const names = Object.fromEntries(people.map(person => [person.id,person.name]));
  const options = people.filter(person => person.status !== 'Inactive' && person.account_status !== 'disabled').map(person => <option key={person.id} value={person.id}>{person.name}</option>);
  const updateLink = (id, change) => onChange({ ...configuration, links: configuration.links.map(link => link.id === id ? { ...link, responsibilities: { ...defaultResponsibilities(), ...link.responsibilities, [kind]: { ...defaultResponsibilities()[kind], ...link.responsibilities?.[kind], ...change } } } : link) });
  const updatePolicy = (id, change) => onChange({ ...configuration, policies: configuration.policies.map(policy => policy.id === id ? { ...policy, ...change } : policy) });
  const preview = requester ? resolveRoute(configuration,people,{requester,kind,days:Number(days)}) : null;
  if (view === 'responsibilities') return <div className="wf-settings">
    <div className="wf-intro"><div><h2>Who is responsible?</h2><p>Choose a request type, then enable responsibilities on your reporting connections.</p></div><label>Request type<select value={kind} onChange={event => setKind(event.target.value)}>{REQUEST_TYPES.map(type => <option key={type} value={type}>{labels[type]}</option>)}</select></label></div>
    <div className="wf-note"><ShieldCheck size={16} /><span><strong>Off never means automatic approval.</strong> An enabled approver is required. Reviewers can inspect a request; CC recipients receive only its summary.</span></div>
    <input className="wf-filter" aria-label="Filter responsibilities" placeholder="Find an employee or responsible person…" value={search} onChange={event => setSearch(event.target.value)} />
    <div className="hm-table-scroll"><table className="wf-responsibilities"><thead><tr><th>Employee / responsible person</th><th>Enabled</th><th>Role</th><th>Step</th><th>Backup & availability</th><th>Effective dates</th></tr></thead><tbody>{configuration.links.filter(link => `${names[link.employee]} ${names[link.manager]}`.toLowerCase().includes(search.toLowerCase())).map(link => { const settings = { ...defaultResponsibilities()[kind], ...link.responsibilities?.[kind] }; return <tr key={link.id}>
      <td><strong>{names[link.employee]}</strong><small>→ {names[link.manager]} · {link.type}</small></td>
      <td><button className="wf-switch" role="switch" aria-checked={settings.enabled} aria-label={`${labels[kind]} responsibility for ${names[link.manager]} on ${names[link.employee]}`} onClick={() => updateLink(link.id,{ enabled: !settings.enabled })}><span /></button><small>{settings.enabled ? 'On' : 'Off'}</small></td>
      <td><select aria-label={`Role for ${names[link.manager]}`} value={settings.role} onChange={event => updateLink(link.id,{role:event.target.value})}><option value="approver">Approver</option><option value="reviewer">Reviewer</option><option value="cc">CC only</option></select></td>
      <td><select aria-label={`Approval step for ${names[link.manager]}`} disabled={settings.role !== 'approver'} value={settings.step} onChange={event => updateLink(link.id,{step:Number(event.target.value)})}>{[1,2,3,4,5,6].map(step => <option key={step} value={step}>{step}</option>)}</select><small>Sequential policies</small></td>
      <td><select aria-label={`Backup for ${names[link.manager]}`} value={settings.backup} onChange={event => updateLink(link.id,{backup:event.target.value})}><option value="">No backup</option>{people.filter(person => person.id !== link.employee && person.id !== link.manager && person.status !== 'Inactive' && person.account_status !== 'disabled').map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select><label className="wf-check"><input type="checkbox" checked={settings.unavailable} onChange={event => updateLink(link.id,{unavailable:event.target.checked})} />Use backup now</label></td>
      <td><label>From<input aria-label={`Effective from for ${names[link.manager]}`} type="date" value={settings.from} onChange={event => updateLink(link.id,{from:event.target.value})} /></label><label>Until<input aria-label={`Effective until for ${names[link.manager]}`} type="date" value={settings.until} onChange={event => updateLink(link.id,{until:event.target.value})} /></label></td>
    </tr>; })}</tbody></table>{!configuration.links.length && <div className="hm-table-empty">Add reporting connections in the graph or reporting table first.</div>}</div>
  </div>;
  return <div className="wf-settings"><div className="wf-intro"><div><h2>Approval policies</h2><p>Higher priority wins; department and location rules take precedence at equal priority.</p></div><button className="hm-button" onClick={() => onChange({ ...configuration, policies:[...configuration.policies,{...defaultPolicy('leave'),id:crypto.randomUUID(),name:'New leave policy',priority:10}] })}><Plus size={14} />Add policy</button></div>
    <div className="wf-policy-list">{configuration.policies.map(policy => <section className="wf-policy" key={policy.id}><div className="wf-policy-title"><input aria-label="Policy name" value={policy.name} onChange={event => updatePolicy(policy.id,{name:event.target.value})} /><button className="wf-switch" role="switch" aria-checked={policy.enabled} aria-label={`Enable ${policy.name}`} onClick={() => updatePolicy(policy.id,{enabled:!policy.enabled})}><span /></button><button className="wf-icon" aria-label={`Remove ${policy.name}`} onClick={() => onChange({ ...configuration, policies:configuration.policies.filter(item => item.id !== policy.id) })}><Trash2 size={14} /></button></div><div className="wf-policy-fields">
      <label>Request type<select value={policy.kind} onChange={event => updatePolicy(policy.id,{kind:event.target.value})}>{REQUEST_TYPES.map(type => <option key={type} value={type}>{labels[type]}</option>)}</select></label>
      <label>Approval rule<select value={policy.mode} onChange={event => updatePolicy(policy.id,{mode:event.target.value})}><option value="any">Any one approver</option><option value="all">All approvers</option><option value="sequential">In sequence</option></select></label>
      <label>Department<select value={policy.department} onChange={event => updatePolicy(policy.id,{department:event.target.value})}><option value="">All departments</option>{[...new Set(people.map(p => p.department).filter(Boolean))].map(value => <option key={value}>{value}</option>)}</select></label>
      <label>Location<select value={policy.location} onChange={event => updatePolicy(policy.id,{location:event.target.value})}><option value="">All locations</option>{[...new Set(people.map(p => p.location).filter(Boolean))].map(value => <option key={value}>{value}</option>)}</select></label>
      <label>Include approval steps through<select value={policy.maxStep || 6} onChange={event => updatePolicy(policy.id,{maxStep:Number(event.target.value)})}>{[1,2,3,4,5,6].map(step => <option key={step} value={step}>Step {step}</option>)}</select></label>
      <label>Priority<input type="number" min="0" max="1000" value={policy.priority} onChange={event => updatePolicy(policy.id,{priority:Number(event.target.value)})} /></label>
      {policy.kind === 'leave' && <><label>Minimum calendar days<input type="number" min="1" max="366" value={policy.minDays} onChange={event => updatePolicy(policy.id,{minDays:Number(event.target.value)})} /></label><label>Maximum calendar days<input type="number" min="1" max="366" value={policy.maxDays} onChange={event => updatePolicy(policy.id,{maxDays:Number(event.target.value)})} /></label></>}
      <label>Remind after (hours)<input type="number" min="1" max="8760" value={policy.reminderHours} onChange={event => updatePolicy(policy.id,{reminderHours:Number(event.target.value)})} /></label>
      <label>Escalate after (hours)<input type="number" min="1" max="8760" value={policy.escalationHours} onChange={event => updatePolicy(policy.id,{escalationHours:Number(event.target.value)})} /></label>
      <label>Escalation approver<select value={policy.escalationUser} onChange={event => updatePolicy(policy.id,{escalationUser:event.target.value})}><option value="">No automatic escalation</option>{options}</select></label>
    </div></section>)}</div>
    <section className="wf-preview"><h2>Routing preview</h2><p>Preview your current draft before publishing. Existing requests retain their saved route.</p><div className="wf-policy-fields"><label>Employee<select value={requester} onChange={event => setRequester(event.target.value)}><option value="">Select employee</option>{options}</select></label><label>Request type<select value={kind} onChange={event => setKind(event.target.value)}>{REQUEST_TYPES.map(type => <option key={type} value={type}>{labels[type]}</option>)}</select></label>{kind === 'leave' && <label>Calendar days<input type="number" min="1" max="366" value={days} onChange={event => setDays(event.target.value)} /></label>}</div>
      {preview && <><div className="wf-route"><span>{names[requester]}</span><ArrowRight size={15} /><span>{preview.policy?.name || 'No matching policy'}</span><ArrowRight size={15} /><span>{preview.policy?.mode === 'sequential' ? 'In sequence' : preview.policy?.mode === 'all' ? 'All must approve' : 'Any one can approve'}</span></div>{preview.blocked && <div className="wf-warning" role="status"><AlertCircle size={15} />{preview.blocked}</div>}<div className="wf-preview-people">{preview.participants.map(person => <div key={person.userId}><strong>{person.name}</strong><small>{person.role} {person.role === 'approver' ? `· Step ${person.step}` : ''}{person.delegated ? ' · Backup' : ''}</small></div>)}</div></>}
    </section>
  </div>;
}
