import { cacheCompanyShifts } from '../../lib/shiftStore';
import React, { useEffect, useState } from 'react';
import { Clock3, Plus, RefreshCw, Moon, Sun, ArrowUpRight } from 'lucide-react';
import { Modal } from '../../components/ui/Modal';
import { dashboardAdminApi } from '../../lib/dashboardAdminApi';
import '../dashboard/DashboardPage.css';
import './WorkspaceSettings.css';

const days = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const templates = [
  { name: 'Standard office', startTime: '09:00', endTime: '18:00', breakDurationMins: 60, gracePeriodMins: 10, workingDays: days.slice(0,5) },
  { name: 'Early shift', startTime: '06:00', endTime: '14:00', breakDurationMins: 30, gracePeriodMins: 10, workingDays: days.slice(0,6) },
  { name: 'Night shift', startTime: '22:00', endTime: '06:00', breakDurationMins: 30, gracePeriodMins: 10, workingDays: days.slice(0,5) }
];
export function ShiftsPage() {
  const [data,setData] = useState({value:[],revision:0}), [loading,setLoading] = useState(true), [error,setError] = useState(''), [notice,setNotice] = useState('');
  const [editing,setEditing] = useState(null), [workingDays,setWorkingDays] = useState([]), [saving,setSaving] = useState(false);
  async function load() { setLoading(true); setError(''); try { const result = await dashboardAdminApi.configuration('shifts'); setData(result); cacheCompanyShifts(result.value); } catch(e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  function edit(shift) { setError(''); setEditing(shift); setWorkingDays(shift.workingDays); }
  async function save(event) {
    event.preventDefault(); setSaving(true); setError('');
    const values = Object.fromEntries(new FormData(event.currentTarget));
    const shift = { ...editing, ...values, id: editing.id || crypto.randomUUID(), workingDays, breakDurationMins: Number(values.breakDurationMins), gracePeriodMins: Number(values.gracePeriodMins), isDefault: values.isDefault === 'on', isOvernight: values.endTime < values.startTime, status: values.status };
    const next = [...data.value.filter(s => s.id !== shift.id), shift].map(s => shift.isDefault ? {...s,isDefault:s.id===shift.id} : s);
    try { const result = await dashboardAdminApi.saveConfiguration('shifts',next,data.revision); setData(result); cacheCompanyShifts(result.value); setEditing(null); setNotice('Shift profile saved to your company workspace.'); } catch(e) { setError(e.message); } finally { setSaving(false); }
  }
  return <main className="tenant-dashboard workspace-settings"><header className="tenant-header"><div><span className="tenant-eyebrow">WORKSPACE / WORK SCHEDULES</span><h1>Shifts<span>.</span></h1><p>Build reusable schedules with working days, breaks, and arrival grace.</p></div><div className="ws-actions"><button className="tenant-button" disabled={loading} onClick={load}><RefreshCw size={15} />Refresh</button><button className="tenant-button ws-primary" disabled={loading || !!error} onClick={() => edit({...templates[0],name:'',isDefault:!data.value.length,status:'Active'})}><Plus size={15} />Create shift</button></div></header>
    <section className="tenant-stats">{[['Shift profiles',data.value.length,'Saved company schedules'],['Active shifts',data.value.filter(s => s.status==='Active').length,'Available schedule profiles'],['Default schedule',data.value.find(s => s.isDefault)?.name || 'Not set','Your company’s reference shift']].map(([label,value,note]) => <div className="tenant-stat" key={label}><div>{label}<Clock3 size={17} /></div><strong>{loading ? '—' : value}</strong><p>{note}</p></div>)}</section>
    {notice && <p className="ws-notice" role="status">{notice}</p>}{error && !editing && <p className="ws-error" role="alert">{error}</p>}
    <section className="tenant-panel"><div className="tenant-panel-head"><div><h2>Start with a template</h2><p>Review the times and working days before saving.</p></div></div><div className="ws-template-grid">{templates.map(t => <button className="ws-template" key={t.name} disabled={loading || !!error} onClick={() => edit({...t,isDefault:!data.value.length,status:'Active'})}>{t.name==='Night shift' ? <Moon size={20} /> : <Sun size={20} />}<strong>{t.name}</strong><span>{t.startTime} – {t.endTime} · {t.breakDurationMins} min break</span><small>Use template <ArrowUpRight size={13} /></small></button>)}</div></section>
    <section className="tenant-panel ws-section"><div className="tenant-panel-head"><div><h2>Company shift profiles</h2><p>These profiles are stored centrally. Employee roster assignment and punch enforcement are managed separately.</p></div></div><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Shift</th><th>Hours</th><th>Working days</th><th>Break / grace</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.value.map(s => <tr key={s.id}><td><strong>{s.name}</strong><small>{s.isDefault ? 'Default schedule' : s.isOvernight ? 'Overnight schedule' : 'Day schedule'}</small></td><td>{s.startTime} – {s.endTime}</td><td>{s.workingDays.join(', ')}</td><td>{s.breakDurationMins} / {s.gracePeriodMins} min</td><td>{s.status}</td><td><button className="tenant-button" onClick={() => edit(s)}>Edit shift</button></td></tr>)}</tbody></table>{!data.value.length && <p className="tenant-empty">{loading ? 'Loading shifts...' : 'Choose a template or create your first company shift.'}</p>}</div></section>
    {editing && <Modal isOpen title={editing.id ? 'Edit shift' : 'Create shift'} size="lg" onClose={() => !saving && setEditing(null)}><form className="ws-form" onSubmit={save}><label>Shift name<input name="name" defaultValue={editing.name} required maxLength={100} disabled={saving} /></label><div className="ws-form-grid"><label>Start time<input type="time" name="startTime" defaultValue={editing.startTime} required disabled={saving} /></label><label>End time<input type="time" name="endTime" defaultValue={editing.endTime} required disabled={saving} /></label><label>Break (minutes)<input type="number" name="breakDurationMins" min="0" max="240" defaultValue={editing.breakDurationMins} required disabled={saving} /></label><label>Arrival grace (minutes)<input type="number" name="gracePeriodMins" min="0" max="240" defaultValue={editing.gracePeriodMins} required disabled={saving} /></label></div><p className="ws-hint">An end time earlier than the start time is treated as the next day.</p><fieldset disabled={saving}><legend>Working days</legend><div className="ws-days">{days.map(d => <label className="ws-check" key={d}><input type="checkbox" checked={workingDays.includes(d)} onChange={e => setWorkingDays(old => e.target.checked ? [...old,d] : old.filter(v => v!==d))} />{d}</label>)}</div></fieldset><label>Status<select name="status" defaultValue={editing.status} disabled={saving}><option>Active</option><option>Inactive</option></select></label><label className="ws-check"><input type="checkbox" name="isDefault" defaultChecked={editing.isDefault} disabled={saving} />Default company schedule</label>{error && <p className="ws-error" role="alert">{error}</p>}<div className="ws-actions"><button className="tenant-button" type="button" disabled={saving} onClick={() => setEditing(null)}>Cancel</button><button className="tenant-button ws-primary" disabled={saving || !workingDays.length}>{saving ? 'Saving...' : 'Save shift'}</button></div></form></Modal>}
  </main>;
}
