import { PlanSubscription } from './PlanSubscription';
import React, { useEffect, useState } from 'react';
import { ShieldCheck, Users, Clock3, MapPin, CalendarDays, GitBranch, FileText, Mail, ArrowUpRight, KeyRound } from 'lucide-react';
import { canUsePage } from '../../../shared/dashboardAccess.mjs';
import { dashboardAdminApi } from '../../lib/dashboardAdminApi';
import { companyAuth } from '../../lib/companyAuth';
import '../dashboard/DashboardPage.css';
import './WorkspaceSettings.css';

const links = [[Users,'dashboard-users','Dashboard users','Grant employees access within your company plan limit.'],[Clock3,'shifts','Shift profiles','Working hours, breaks, grace periods and templates.'],[MapPin,'geofence-rules','Geofence & photo rules','Campus sites, location boundaries and photo requirements.'],[CalendarDays,'company-calendar','Calendar & leave policies','Holidays, leave entitlements and company dates.'],[GitBranch,'hierarchy','Approval workflows','Responsibilities, approvers and escalation settings.'],[FileText,'documents','Company documents','Policies, employee records and verification.'],[Mail,'helpdesk','HR communications','Announcements, messages and private grievance reviews.']];
export function WorkspaceSettingsPage({ currentUser, onNavigate, onLogout }) {
  const [data,setData] = useState(null), [error,setError] = useState(''), [notice,setNotice] = useState(''), [saving,setSaving] = useState(false);
  useEffect(() => { let alive=true; dashboardAdminApi.configuration('settings').then(v => { if(alive) setData(v); }).catch(e => { if(alive) setError(e.message); }); return () => { alive=false; }; },[]);
  async function save(event) { event.preventDefault(); const value=Object.fromEntries(new FormData(event.currentTarget)); setSaving(true);setError('');setNotice('');try { setData(await dashboardAdminApi.saveConfiguration('settings',value,data.revision));setNotice('Company contact details saved.'); } catch(e) {setError(e.message);} finally {setSaving(false);} }
  async function password(event) { event.preventDefault(); const values=Object.fromEntries(new FormData(event.currentTarget)); if(values.next!==values.confirm) {setError('New passwords do not match.');return;}setSaving(true);setError('');try {await companyAuth.changePassword(localStorage.getItem('pulse_hrms_token'),values.current,values.next);onLogout();} catch(e) {setError(e.message);} finally {setSaving(false);} }
  return <main className="tenant-dashboard workspace-settings"><header className="tenant-header"><div><span className="tenant-eyebrow">WORKSPACE / CONFIGURATION</span><h1>Settings<span>.</span></h1><p>Manage your company workspace, security, and HR configuration.</p></div><span className="ws-role"><ShieldCheck size={16} />{currentUser.role==='company_admin' ? 'Super Admin' : 'Dashboard user'}</span></header>
    <div className="ws-account"><div><strong>{currentUser.username}</strong><p>{currentUser.role==='company_admin' ? 'Full company control, including dashboard-user access.' : 'Your Super Admin controls which pages you can use.'}</p></div><span>Company workspace</span></div>
    {error && <p className="ws-error" role="alert">{error}</p>}{notice && <p className="ws-notice" role="status">{notice}</p>}
    {currentUser.role === 'company_admin' && <PlanSubscription currentUser={currentUser} />}
    <section className="ws-settings-grid">{links.filter(([,page]) => canUsePage(currentUser,page)).map(([Icon,page,title,description]) => <button className="ws-setting-card" key={page} onClick={() => onNavigate(page)}><span><Icon size={20} /></span><div><h2>{title}</h2><p>{description}</p></div><ArrowUpRight size={16} /></button>)}</section>
    <div className="ws-settings-grid ws-section"><section className="tenant-panel"><div className="tenant-panel-head"><div><h2>Company HR contact</h2><p>Shared contact details for your HR team.</p></div><Mail size={18} /></div>{data ? <form className="ws-form ws-panel-body" onSubmit={save}><label>HR email<input name="hrEmail" type="email" maxLength={254} defaultValue={data.value.hrEmail} disabled={saving} placeholder="hr@company.com" /></label><label>Support phone<input name="supportPhone" type="tel" maxLength={50} defaultValue={data.value.supportPhone} disabled={saving} /></label><label>HR contact note<textarea name="announcementFooter" rows={3} maxLength={500} defaultValue={data.value.announcementFooter} disabled={saving} placeholder="Office hours or guidance for contacting HR" /></label><button className="tenant-button ws-primary" disabled={saving}>Save contact details</button></form> : <p className="tenant-empty">{error ? 'Settings unavailable.' : 'Loading settings...'}</p>}</section>
    <section className="tenant-panel"><div className="tenant-panel-head"><div><h2>Password & sign-in</h2><p>A password change signs out your existing sessions.</p></div><KeyRound size={18} /></div><form className="ws-form ws-panel-body" onSubmit={password}><label>Current password<input type="password" name="current" required autoComplete="current-password" disabled={saving} /></label><label>New password<input type="password" name="next" required minLength={6} maxLength={128} autoComplete="new-password" disabled={saving} /></label><label>Confirm new password<input type="password" name="confirm" required minLength={6} maxLength={128} autoComplete="new-password" disabled={saving} /></label><button className="tenant-button" disabled={saving}>Change password & sign out</button></form></section></div>
  </main>;
}
