import React, { useEffect, useRef, useState } from 'react';
import { Plus, Save, Eye, Copy, FileText, Layers, Users, Download, Trash2, ZoomIn, X } from 'lucide-react';
import { PageHeader } from '../ui/PageHeader';
import { EmployeeDirectory } from '../employees/EmployeeDirectory';
import { PAYSLIP_DESIGNS, EARNINGS, DEDUCTIONS, PAY_MONTHS, newPayslipTemplate, normalizeSalary, validateTemplate } from '../../lib/payslipModel';
import { createPayslipDocument } from '../../lib/payslipDocument';
import { payslipApi } from '../../lib/payslipApi';
import { getMonthlySalary, saveMonthlySalary } from '../../lib/salaryStore';
import { PayslipRecords } from './PayslipRecords';
import './PayslipStudio.scss';

export function PayslipStudio({ api, children }) {
  const [tab, setTab] = useState('salary'), [configuration, setConfiguration] = useState({ templates: [], groups: [], assignments: [], storage: null });
  const [employees, setEmployees] = useState([]), [person, setPerson] = useState(null), [peopleLoading, setPeopleLoading] = useState(true), [peopleError, setPeopleError] = useState('');
  const [template, setTemplate] = useState(newPayslipTemplate()), [group, setGroup] = useState({ name: '', type: '', template_id: '' });
  const [assignment, setAssignment] = useState({ group_id: '', template_id: '', auto_generate: true });
  const [month, setMonth] = useState(PAY_MONTHS[new Date().getMonth()]), [year, setYear] = useState(String(new Date().getFullYear()));
  const [multi, setMulti] = useState(false), [selectedIds, setSelectedIds] = useState([]), [salaryLoading, setSalaryLoading] = useState(false);
  const [salary, setSalary] = useState(normalizeSalary({})), [autoDownload, setAutoDownload] = useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [preview, setPreview] = useState(''), [refresh, setRefresh] = useState(0);
  const previewDialog = useRef(null);
  useEffect(() => { if (preview) previewDialog.current?.showModal(); }, [preview]);
  async function loadConfiguration() { const data = await payslipApi.configuration(); setConfiguration(data); return data; }
  useEffect(() => { loadConfiguration().catch(err => setError(err.message)); }, []);
  useEffect(() => { let active = true; setPeopleLoading(true); api.getAllUsers({ liveOnly: true }).then(result => { if (active) { setEmployees(result.data || []); setPerson(current => current || result.data?.[0] || null); } }).catch(err => { if (active) setPeopleError(err.message); }).finally(() => { if (active) setPeopleLoading(false); }); return () => { active = false; }; }, [api]);
  useEffect(() => { setAssignment(configuration.assignments.find(item => item.id === person?.userid) || { group_id: '', template_id: '', auto_generate: true }); }, [person?.userid, configuration.assignments]);
  useEffect(() => {
    if (!person) return;
    let active = true; setSalaryLoading(true);
    setSalary(normalizeSalary(getMonthlySalary(person.userid, year, month) || {}));
    payslipApi.records(person.userid).then(records => { const saved = records.find(record => record.month === month && record.year === String(year)); if (active && saved) setSalary(saved.salary); }).catch(err => { if (active) setError(err.message); }).finally(() => { if (active) setSalaryLoading(false); });
    return () => { active = false; };
  }, [person?.userid, month, year]);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  async function run(action) { setBusy(true); setError(''); setNotice(''); try { await action(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  const change = (key, value) => setTemplate(current => ({ ...current, [key]: value }));
  const effectiveGroup = configuration.groups.find(item => item.id === assignment.group_id);
  const effectiveTemplate = configuration.templates.find(item => item.id === (assignment.template_id || effectiveGroup?.template_id));
  async function uploadImage(event, key) {
    const file = event.target.files?.[0]; if (!file) return;
    try {
      if (!['image/png', 'image/jpeg'].includes(file.type) || file.size > 500000) throw new Error('Choose a PNG or JPEG smaller than 500 KB.');
      const data = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(new Error('Cannot read this image.')); reader.readAsDataURL(file); });
      change(key, data);
    } catch (err) { setError(err.message); } finally { event.target.value = ''; }
  }
  function previewTemplate(value = template) {
    try {
      const valid = validateTemplate({ ...value, name: value.name || 'Design example', company_name: value.company_name || 'Your company', title: value.title || 'Salary payslip' });
      const pdf = createPayslipDocument({ employee: person || { userid: 'PREVIEW', first_name: 'Preview' }, salaryRecord: salary, template: valid, month, year });
      setPreview(URL.createObjectURL(pdf.output('blob'))); setError('');
    } catch (err) { setError(err.message); }
  }
  async function saveSalary() {
    if (!person) throw new Error('Select an employee first.');
    await payslipApi.assign({ ...assignment, userid: person.userid });
    const normalized = normalizeSalary(salary);
    const result = await payslipApi.saveSalary({ employee: person, salary: normalized, month, year, generate: autoDownload });
    saveMonthlySalary(person.userid, year, month, normalized);
    setRefresh(value => value + 1); window.dispatchEvent(new Event('payslip-records-changed'));
    await loadConfiguration();
    if (result.status === 'failed') { setNotice('Salary and template revision saved to the database.'); throw new Error(result.error); }
    setNotice(result.status === 'ready' ? 'Salary saved and PDF stored in R2. It is available in Payroll & CTC.' : 'Salary saved. Generate the PDF from the payslip list when ready.');
    if (autoDownload && result.status === 'ready') await payslipApi.download(result.id);
  }
  let totals; try { totals = normalizeSalary(salary); } catch { totals = null; }
  const componentRows = (fields, customKey) => <div className="ps-components">{fields.map(([key, label]) => <label key={key}>{label}<input type="number" min="0" step="0.01" value={salary[key]} onChange={e => setSalary({ ...salary, [key]: e.target.value })} /></label>)}{salary[customKey].map((row, index) => <div className="ps-custom-row" key={index}><input aria-label="Component name" placeholder="Component name" value={row.name} onChange={e => setSalary({ ...salary, [customKey]: salary[customKey].map((item, i) => i === index ? { ...item, name: e.target.value } : item) })} /><input aria-label="Component amount" type="number" min="0" step="0.01" value={row.amount} onChange={e => setSalary({ ...salary, [customKey]: salary[customKey].map((item, i) => i === index ? { ...item, amount: e.target.value } : item) })} /><button type="button" className="ps-button" aria-label="Remove component" onClick={() => setSalary({ ...salary, [customKey]: salary[customKey].filter((_, i) => i !== index) })}><Trash2 size={13} /></button></div>)}<button type="button" className="ps-button" onClick={() => setSalary({ ...salary, [customKey]: [...salary[customKey], { name: '', amount: 0 }] })}><Plus size={13} />Custom component</button></div>;
  return <div className="payslip-studio">
    <PageHeader title="Salary & Payslip Studio" subtitle="Create company templates, organize payroll groups, and issue a payslip for each person." breadcrumbs={['HRMS', 'Payroll & CTC', 'Edit Salary & Structure']} />

    {configuration.storage?.localDevelopment && <p className="ps-notice">Local admin development session. Production requires your verified authentication service.</p>}
    {error && <div role="alert" className="ps-error">{error} <button type="button" onClick={() => run(loadConfiguration)}>Retry connection</button></div>}{notice && <p role="status" className="ps-notice">{notice}</p>}
    <div className="employee-workspace ps-workspace"><div className="employee-workspace-content ps-content">
      <div className="ps-toolbar ps-split-toolbar"><nav aria-label="Salary workspace"><div className="ps-tab-primary"><button type="button" aria-pressed={tab === 'salary'} onClick={() => setTab('salary')}><Layers size={15} />Salary & generation</button></div><div className="ps-tab-settings">{[['templates', FileText, 'Payslip templates'], ['groups', Users, 'Groups & assignment'], ['components', Layers, 'Salary components']].map(([id, Icon, label]) => <button type="button" key={id} aria-pressed={tab === id} onClick={() => setTab(id)}><Icon size={15} />{label}</button>)}</div></nav></div>


      {tab === 'salary' && <><section className="ps-panel"><header><div><span className="ps-eyebrow">SALARY & GENERATION</span><h3>{person ? [person.first_name, person.last_name].filter(Boolean).join(' ') || person.userid : 'Select an employee'}</h3><p>Recorded amounts only. No payment is transferred by this action.</p></div></header><form onSubmit={e => { e.preventDefault(); run(saveSalary); }}><fieldset disabled={busy || !person || salaryLoading}><div className="ps-form-grid"><label>Month<select value={month} onChange={e => setMonth(e.target.value)}>{PAY_MONTHS.map(value => <option key={value}>{value}</option>)}</select></label><label>Year<input required type="number" min="1900" max="2200" value={year} onChange={e => setYear(e.target.value)} /></label></div><div className="ps-pay-columns"><section><h4>Earnings / INR</h4>{componentRows(EARNINGS, 'custom_earnings')}</section><section><h4>Deductions / INR</h4>{componentRows(DEDUCTIONS, 'custom_deductions')}</section></div><div className="ps-form-grid">{[['pay_date', 'Payment date', 'date'], ['paid_days', 'Paid days', 'number'], ['bank_name', 'Bank name', 'text'], ['bank_account', 'Account number (masked in PDF)', 'text'], ['transaction_ref', 'Transaction reference', 'text']].map(([key, label, type]) => <label key={key}>{label}<input type={type} min={type === 'number' ? 0 : undefined} max={type === 'number' ? 31 : undefined} step={type === 'number' ? '.5' : undefined} value={salary[key]} onChange={e => setSalary({ ...salary, [key]: e.target.value })} /></label>)}</div><div className="ps-totals"><span>Gross<strong>INR {totals?.monthly_gross.toLocaleString('en-IN') ?? '--'}</strong></span><span>Deductions<strong>INR {totals?.total_deductions.toLocaleString('en-IN') ?? '--'}</strong></span><span>Net pay<strong>INR {totals?.monthly_net.toLocaleString('en-IN') ?? '--'}</strong></span></div><label className="ps-check"><input type="checkbox" checked={autoDownload} onChange={e => setAutoDownload(e.target.checked)} />Download automatically after generation</label><div className="ps-actions"><span>Template: {effectiveTemplate?.name || 'Choose a template in Groups & assignment'}</span><button className="ps-button ps-primary" disabled={!effectiveTemplate} type="submit"><Save size={14} />{busy ? 'Saving & generating...' : 'Save salary'}</button></div></fieldset></form></section><PayslipRecords employee={person} refreshKey={refresh} /></>}


{tab === 'components' && <div className="ps-component-library">{children}</div>}
      {tab === 'templates' && <>
        <section className="ps-panel"><header><div><span className="ps-eyebrow">01 / CHOOSE A DESIGN</span><h3>Three foundations. Your company identity.</h3><p>Save up to five variants per design. Issued PDFs retain their original template revision.</p></div></header><div className="ps-designs">{PAYSLIP_DESIGNS.map(design => <button type="button" key={design.id} aria-pressed={template.design === design.id} onClick={() => { const next = { ...template, design: design.id, id: undefined, version: undefined }; setTemplate(next); previewTemplate(next); }}><div className={'ps-mini ps-mini-' + design.id}><i /><b /><span /><span /><hr /><span /><span /><b /></div><strong>{design.name}</strong><small>{design.description}</small><span className="ps-enlarge"><ZoomIn size={14} /> View example</span><em>{configuration.templates.filter(item => item.design === design.id).length} / 5 variants</em></button>)}</div></section>
        <section className="ps-panel"><header><div><span className="ps-eyebrow">02 / CUSTOMIZE & SAVE</span><h3>{template.id ? 'Edit ' + template.name : 'Company identity & template'}</h3><p>Company details, logo and signature are stored with each saved variant.</p></div><select aria-label="Edit saved template" value={template.id || ''} onChange={e => { setTemplate(configuration.templates.find(item => item.id === e.target.value) || newPayslipTemplate(template.design)); setPreview(''); }}><option value="">New variant</option>{configuration.templates.map(item => <option key={item.id} value={item.id}>{item.name} / {item.design} / v{item.version}</option>)}</select></header>
          <form onSubmit={e => { e.preventDefault(); run(async () => { const saved = await payslipApi.saveTemplate(template); setTemplate(saved); await loadConfiguration(); setNotice('Template saved to the database.'); }); }}><fieldset disabled={busy}>
            <div className="ps-form-grid">{[['name', 'Variant name'], ['company_name', 'Company name'], ['title', 'Document title'], ['registration', 'Registration / tax identifiers']].map(([key, label]) => <label key={key}>{label}<input required={key !== 'registration'} maxLength={120} value={template[key]} onChange={e => change(key, e.target.value)} /></label>)}<label className="ps-wide">Company address<textarea rows={2} maxLength={600} value={template.address} onChange={e => change('address', e.target.value)} /></label><label>Accent color<input type="color" value={template.accent} onChange={e => change('accent', e.target.value)} /></label><label>Authorized signatory<input maxLength={120} value={template.signatory} onChange={e => change('signatory', e.target.value)} /></label><label>Signatory designation<input maxLength={120} value={template.signatory_title} onChange={e => change('signatory_title', e.target.value)} /></label>
            {['logo', 'signature'].map(key => <label key={key} className="ps-image-field">{key === 'logo' ? 'Company logo' : 'Signature image'}<input type="file" accept="image/png,image/jpeg" onChange={e => uploadImage(e, key)} />{template[key] && <><img src={template[key]} alt={key + ' preview'} /><button type="button" className="ps-button" onClick={() => change(key, '')}>Remove image</button></>}<small>PNG or JPEG, up to 500 KB</small></label>)}
            <label className="ps-wide">Statement note<textarea maxLength={600} rows={3} value={template.note} onChange={e => change('note', e.target.value)} /><small>Auto-fill: {'{{employee_name}}'}, {'{{employee_id}}'}, {'{{month}}'}, {'{{year}}'}</small></label><label className="ps-wide">Footer text<textarea maxLength={200} rows={2} value={template.footer} onChange={e => change('footer', e.target.value)} /></label></div>
            <div className="ps-actions"><button type="button" className="ps-button" onClick={() => previewTemplate()}><Eye size={14} />Preview PDF</button>{template.id && <button type="button" className="ps-button" onClick={() => setTemplate(({ id, version, ...rest }) => ({ ...rest, name: rest.name + ' copy' }))}><Copy size={14} />Duplicate variant</button>}<button className="ps-button ps-primary" type="submit"><Save size={14} />{busy ? 'Saving...' : 'Save template'}</button></div></fieldset></form>
        </section>

      </>}
      {tab === 'groups' && <section className="ps-panel"><header><div><span className="ps-eyebrow">PAYROLL GROUPS</span><h3>Create a group or employment type</h3><p>For example, permanent employees, contractors, interns or your own category.</p></div></header><form onSubmit={e => { e.preventDefault(); run(async () => { await payslipApi.saveGroup(group); await loadConfiguration(); setGroup({ name: '', type: '', template_id: '' }); setNotice('Payroll group saved.'); }); }}><fieldset disabled={busy}><div className="ps-form-grid"><label>Group name<input required value={group.name} onChange={e => setGroup({ ...group, name: e.target.value })} /></label><label>Group type<input required list="payroll-group-types" value={group.type} onChange={e => setGroup({ ...group, type: e.target.value })} /><datalist id="payroll-group-types"><option value="Permanent" /><option value="Contractor" /><option value="Intern" /><option value="Consultant" /></datalist></label><label className="ps-wide">Default payslip template<select required value={group.template_id} onChange={e => setGroup({ ...group, template_id: e.target.value })}><option value="">Select saved template</option>{configuration.templates.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><div className="ps-actions">{group.id && <button type="button" className="ps-button" onClick={() => setGroup({ name: '', type: '', template_id: '' })}>Cancel edit</button>}<button className="ps-button ps-primary" type="submit"><Save size={14} />{group.id ? 'Update group' : 'Create group'}</button></div></fieldset></form><div className="ps-group-list">{configuration.groups.map(item => <button type="button" key={item.id} onClick={() => setGroup(item)}><strong>{item.name}</strong><span>{item.type} / {configuration.templates.find(t => t.id === item.template_id)?.name}</span><small>Edit group</small></button>)}</div></section>}
      {(tab === 'groups') && <section className="ps-panel"><header><div><span className="ps-eyebrow">PERSONAL ASSIGNMENT</span><h3>{multi && tab === 'groups' ? selectedIds.length + ' selected people' : person ? person.first_name + ' ' + (person.last_name || '') : 'Select an employee'}</h3><p>An individual override takes precedence over the group template.</p></div></header><form onSubmit={e => { e.preventDefault(); run(async () => { const targets = multi && tab === 'groups' ? selectedIds : [person.userid]; if (!targets.length) throw new Error('Select at least one employee.'); let count = 0; for (const userid of targets) { try { await payslipApi.assign({ ...assignment, userid }); count++; } catch (error) { await loadConfiguration(); throw new Error(count + ' assignments saved. ' + error.message); } } await loadConfiguration(); setNotice('Assignment saved for ' + count + ' people.'); }); }}><fieldset disabled={busy || !person}><div className="ps-form-grid"><label>Payroll group<select value={assignment.group_id} onChange={e => setAssignment({ ...assignment, group_id: e.target.value })}><option value="">No group</option>{configuration.groups.map(item => <option key={item.id} value={item.id}>{item.name} / {item.type}</option>)}</select></label><label>Individual template override<select value={assignment.template_id} onChange={e => setAssignment({ ...assignment, template_id: e.target.value })}><option value="">Use group template</option>{configuration.templates.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="ps-check ps-wide"><input type="checkbox" checked={assignment.auto_generate} onChange={e => setAssignment({ ...assignment, auto_generate: e.target.checked })} />Automatically generate and upload when salary is saved</label></div><div className="ps-actions"><span>Effective template: {effectiveTemplate?.name || 'Not assigned'}</span><button className="ps-button ps-primary" type="submit">Save assignment</button></div></fieldset></form></section>}

    </div><EmployeeDirectory employees={employees} selectedId={person?.userid} onSelect={setPerson} loading={peopleLoading} error={peopleError} subtitle="Select a person for template previews, assignment and salary." multi={tab === 'groups' && multi} selectedIds={selectedIds} onToggle={id => setSelectedIds(ids => ids.includes(id) ? ids.filter(value => value !== id) : [...ids, id])} onSelectAll={setSelectedIds} onClearAll={() => setSelectedIds([])} headerExtra={tab === 'groups' ? <button type="button" className="ps-button" onClick={() => { setMulti(!multi); setSelectedIds(person ? [person.userid] : []); }}>{multi ? 'Select one person' : 'Assign multiple people'}</button> : null} /></div>
    <dialog ref={previewDialog} className="ps-preview-modal" onCancel={() => setPreview('')} onClose={() => setPreview('')} aria-labelledby="ps-preview-title">
      <header><div><span className="ps-eyebrow">DESIGN PREVIEW / NOT ISSUED</span><h3 id="ps-preview-title">{PAYSLIP_DESIGNS.find(item => item.id === template.design)?.name} payslip example</h3><p>Uses current salary inputs. Blank company details show preview placeholders.</p></div><button autoFocus type="button" className="ps-button" aria-label="Close preview" onClick={() => previewDialog.current.close()}><X size={18} /></button></header>
      {preview && <iframe title="Payslip PDF example" src={preview} className="ps-pdf-preview" />}
    </dialog>
  </div>;
}
