import { deleteAssetList } from './deleteAssetList.mjs';
import { createCanvas } from '@napi-rs/canvas';
import { webpSize } from './assetImageValidation.mjs';
import { fittedImageSize } from '../src/lib/assetImageCompression.js';
import { assetPhotos } from './assetPhotos.mjs';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { talentHandle } from './talent.mjs';
import { routePages, parsePages } from '../shared/dashboardAccess.mjs';
const sqlite = new DatabaseSync(':memory:');
sqlite.exec("PRAGMA foreign_keys=ON; CREATE TABLE companies(company_id TEXT PRIMARY KEY); INSERT INTO companies VALUES('a'),('b'); CREATE TABLE employees(company_id TEXT,user_id TEXT); INSERT INTO employees VALUES('a','employee-a'),('b','employee-b');");
sqlite.exec(readFileSync(new URL('../migrations/hrms/0009_talent_operations.sql', import.meta.url), 'utf8'));
sqlite.exec(readFileSync(new URL('../migrations/hrms/0010_asset_issues.sql', import.meta.url), 'utf8'));
const prepare = (sql, values = []) => ({ bind: (...params) => prepare(sql, params), first: async () => sqlite.prepare(sql).get(...values), all: async () => ({ results: sqlite.prepare(sql).all(...values) }), run: async () => sqlite.prepare(sql).run(...values) });
const db = { prepare };
const call = (collection, body, id = '', company = 'a', role = 'company_admin') => talentHandle({ db, actor: { company_id: company, user_id: 'admin', role }, path: `/api/v1/talent/${collection}${id ? '/' + id : ''}`, method: body ? 'POST' : 'GET', body, url: new URL('https://test.invalid') });
const reject = async (promise, status) => assert.rejects(promise, error => error.status === status);
try {
  const job = await call('jobs', { title: 'Engineer', department: 'Engineering', positions: 2, status: 'Open' });
  assert.equal(job.revision, 0);
  assert.equal((await call('jobs', undefined, '', 'b')).length, 0);
  await reject(call('jobs', undefined, '', 'a', 'employee'), 403);
  await reject(call('jobs', { ...job, title: 'Wrong company' }, job.id, 'b'), 404);
  const edited = await call('jobs', { ...job, status: 'Closed' }, job.id);
  assert.equal(edited.revision, 1);
  await reject(call('jobs', { ...job, title: 'Stale edit' }, job.id), 409);
  await reject(call('jobs', { ...job, positions: 1.5 }), 400);
  await reject(call('__proto__', {}), 404);
  const candidate = { title: 'Candidate', email: 'person@example.com', job_id: job.id, status: 'Applied' };
  await call('candidates', candidate);
  await reject(call('candidates', { ...candidate, email: 'PERSON@example.com' }), 409);
  await reject(call('candidates', candidate, '', 'b'), 400);
  await reject(call('candidates', { ...candidate, email: 'other@example.com', interview_date: '2026-02-30' }), 400);
  const plan = { title: 'Joining plan', employee_id: 'employee-a', owner_id: 'employee-a', start_date: '2026-10-01', due_date: '2026-10-05', status: 'In progress', checklist: [{ title: 'Prepare access', done: false }] };
  for (const collection of ['onboarding', 'offboarding']) {
    const saved = await call(collection, plan);
    await reject(call(collection, { ...saved, employee_id: 'employee-b' }, saved.id), 400);
    await reject(call(collection, { ...saved, status: 'Completed' }, saved.id), 400);
    const complete = await call(collection, { ...saved, status: 'Completed', checklist: [{ title: 'Prepare access', done: true }] }, saved.id);
    assert.equal(complete.status, 'Completed');
    await reject(call(collection, { ...plan, due_date: '2026-09-01' }), 400);
  }
  const goal = { title: 'Improve resolution time', employee_id: 'employee-a', due_date: '2026-12-31', status: 'On track', key_results: [{ title: 'Tickets resolved', target: 100, current: 50 }] };
  await call('goals', goal);
  await reject(call('goals', { ...goal, status: 'Completed' }), 400);
  await reject(call('goals', { ...goal, status: 'Completed', key_results: [{ title: 'Nearly done', target: 100, current: 99.9 }] }), 400);
  await reject(call('goals', { ...goal, key_results: [{ title: 'Invalid', target: 0, current: 1 }] }), 400);
  const asset = { title: 'Laptop', serial_number: 'ASSET-1', category: 'Laptop', condition: 'New', status: 'Available' };
  const savedAsset = await call('assets', asset);
  assert.equal(savedAsset.list_id, '');
  const assetList = await call('asset_lists', { title: 'Office furniture', types: ['Chair', 'Desk'] });
  const furniture = await call('assets', { ...asset, serial_number: 'CHAIR-1', category: 'Other', custom_type: 'Chair', list_id: assetList.id });
  assert.equal(furniture.list_id, assetList.id);
  assert.deepEqual(assetList.types, ['Chair', 'Desk']);
  await reject(call('asset_lists', { title: ' OFFICE FURNITURE ', types: ['Chair'] }), 409);
  await reject(call('asset_lists', { title: ' IT assets list ', types: ['Chair'] }), 409);
  await reject(call('assets', { ...asset, title: ' LAPTOP ', serial_number: 'DUPLICATE-NAME' }), 409);
  await call('asset_lists', { title: 'Office furniture', types: ['Chair'] }, '', 'b');
  const renamedList = await call('asset_lists', { title: 'Different list', types: ['Chair'] });
  await reject(call('asset_lists', { ...renamedList, title: 'office furniture' }, renamedList.id), 409);
  await call('asset_lists', { ...renamedList, notes: 'Same name edit allowed' }, renamedList.id);
  assert.equal(furniture.processor, '');
  await reject(call('asset_lists', { title: 'Too many', types: ['A', 'B', 'C', 'D', 'E', 'F'] }), 400);
  await reject(call('asset_lists', { title: 'Duplicate', types: ['Chair', ' chair '] }), 400);
  await reject(call('asset_lists', { title: 'Empty', types: [' '] }), 400);
  await call('asset_lists', { title: 'Five types', types: ['A', 'B', 'C', 'D', 'E'] });
  await reject(call('assets', { ...furniture, custom_type: 'Invalid' }, furniture.id), 400);
  const updatedFurniture = await call('assets', { ...furniture, processor: 'Hidden', specifications: 'Hidden' }, furniture.id);
  assert.equal(updatedFurniture.processor, '');
  assert.equal(updatedFurniture.specifications, '');
  assert.equal((await call('asset_lists')).find(list => list.id === assetList.id).title, 'Office furniture');
  await reject(call('assets', { ...asset, serial_number: 'FOREIGN-LIST', list_id: assetList.id }, '', 'b'), 400);
  await reject(call('asset_lists', { title: '   ' }), 400);

  await reject(call('assets', { ...asset, serial_number: 'asset-1' }), 409);
  await call('assets', asset, '', 'b');
  await reject(call('assets', { ...savedAsset, status: 'Assigned' }, savedAsset.id), 400);
  const issue = { asset_id: savedAsset.id, employee_id: 'employee-a', issue_date: '2026-10-01', status: 'Issued' };
  const issued = await call('asset_issues', issue);
  await reject(call('asset_issues', issue), 409);
  await reject(call('asset_issues', { ...issue, employee_id: 'employee-b' }), 400);
  await reject(call('assets', { ...savedAsset, status: 'Retired' }, savedAsset.id), 400);
  await reject(call('asset_issues', { ...issued, status: 'Received' }, issued.id), 400);
  await reject(call('asset_issues', { ...issued, status: 'Received', received_date: '2026-09-30', acknowledgement_note: 'Received in good condition' }, issued.id), 400);
  const received = await call('asset_issues', { ...issued, status: 'Received', received_date: '2026-10-02', acknowledgement_note: 'Received in good condition' }, issued.id);
  await reject(call('asset_issues', { ...received, status: 'Returned', return_condition: 'Good' }, received.id), 400);
  const returned = await call('asset_issues', { ...received, status: 'Returned', return_date: '2026-11-01', return_condition: 'Good' }, received.id);
  await reject(call('asset_issues', { ...returned, status: 'Issued', received_date: '', return_date: '' }, returned.id), 400);
  const reissued = await call('asset_issues', { ...issue, issue_date: '2026-11-02', notes: 'Second handover' });
  const directReturn = await call('asset_issues', { ...reissued, status: 'Returned', return_date: '2026-11-03', return_condition: 'Good', notes: 'Returned without receipt acknowledgement' }, reissued.id);
  assert.equal(directReturn.notes, 'Returned without receipt acknowledgement');
  assert.equal((await call('asset_issues')).find(item => item.id === directReturn.id).return_date, '2026-11-03');
  const priced = await call('assets', { ...asset, title: 'Private laptop', serial_number: 'PRIVATE', purchase_price: 80000, currency: 'INR', purchase_date: '2026-01-01', vendor: 'Vendor', warranty_until: '2027-01-01' });
  const delegated = (method, body, id = '') => talentHandle({ db, actor: { company_id: 'a', user_id: 'delegate', role: 'company_admin', original_role: 'employee' }, path: '/api/v1/talent/assets' + (id ? '/' + id : ''), method, body, url: new URL('https://test.invalid') });
  const safe = (await delegated('GET')).find(item => item.id === priced.id);
  assert.equal(Object.hasOwn(safe, 'purchase_price'), false);
  assert.equal(Object.hasOwn(safe, 'vendor'), false);
  await reject(delegated('POST', { ...safe, purchase_price: 1 }, safe.id), 403);
  await delegated('POST', { ...safe, title: 'Updated equipment name' }, safe.id);
  assert.equal((await call('assets')).find(item => item.id === priced.id).purchase_price, 80000);
  await reject(call('assets', { ...asset, serial_number: 'OTHER', category: 'Other' }), 400);
  const other = await call('assets', { ...asset, title: 'Security token', serial_number: 'OTHER', category: 'Other', custom_type: 'Security token' });
  assert.equal(other.custom_type, 'Security token');
  await reject(call('assets', { ...asset, serial_number: 'BAD-PRICE', purchase_price: -1 }), 400);
  const storedPhotos = new Map();
  const bucket = { put: async (key, bytes, metadata) => storedPhotos.set(key, { body: bytes, ...metadata }), get: async key => storedPhotos.get(key), delete: async key => storedPhotos.delete(key) };
  const webp = (width, height) => createCanvas(width, height).encodeSync('webp');
  const fullImage = webp(800, 400), thumbnailImage = webp(160, 80);
  assert.deepEqual(fittedImageSize(1600, 800, 800), { width: 800, height: 400 });
  assert.deepEqual(fittedImageSize(300, 600, 800), { width: 300, height: 600 });
  assert.deepEqual(webpSize(fullImage), { width: 800, height: 400 });
  const photoRequest = (record, stage, { company = 'a', method = 'POST', photo = '', variant = '', bytes = fullImage, thumbnail = thumbnailImage } = {}) => {
    const url = new URL('https://test.invalid/photos?stage=' + stage + '&revision=' + record.revision + '&photo=' + photo + '&variant=' + variant);
    const form = new FormData(); form.append('image', new Blob([bytes], { type: 'image/webp' }), 'image.webp'); form.append('thumbnail', new Blob([thumbnail], { type: 'image/webp' }), 'thumbnail.webp');
    return assetPhotos({ db, env: { HRMS_DOCUMENTS: bucket }, actor: { role: 'company_admin', company_id: company, user_id: 'admin' }, collection: 'asset_issues', id: record.id, url, request: new Request(url, { method, ...(method === 'POST' ? { body: form } : {}) }) });
  };
  let photoRecord = { ...directReturn, ...await photoRequest(directReturn, 'returned') };
  await reject(photoRequest(photoRecord, 'returned', { company: 'b' }), 404);
  await reject(photoRequest(photoRecord, 'returned', { bytes: new Uint8Array([1,2,3]) }), 400);
  await reject(photoRequest(photoRecord, 'returned', { bytes: webp(801, 400) }), 400);
  await reject(photoRequest(photoRecord, 'returned', { thumbnail: webp(161, 80) }), 400);
  const firstPhoto = photoRecord.photos.returned[0];
  assert.equal(storedPhotos.size, 2);
  assert.equal(firstPhoto.width, 800);
  const thumbnailResponse = await photoRequest(photoRecord, 'returned', { method: 'GET', photo: firstPhoto.id, variant: 'thumbnail' });
  assert.equal(thumbnailResponse.headers.get('Content-Type'), 'image/webp');
  assert.deepEqual(webpSize(new Uint8Array(await thumbnailResponse.arrayBuffer())), { width: 160, height: 80 });
  const originalPut = bucket.put;
  bucket.put = async (key, bytes, metadata) => { if (key.endsWith('thumbnail.webp')) throw new Error('Simulated storage failure'); return originalPut(key, bytes, metadata); };
  await assert.rejects(photoRequest(photoRecord, 'issued'), /Simulated storage failure/);
  assert.equal(storedPhotos.size, 2);
  bucket.put = originalPut;
  assert.equal((await photoRequest(photoRecord, 'returned', { method: 'GET', photo: firstPhoto.id })).status, 200);
  await reject(photoRequest(directReturn, 'returned'), 409);
  await reject(photoRequest(photoRecord, 'returned'), 400);
  const preserved = await call('asset_issues', { ...photoRecord, photos: {}, notes: 'Evidence retained' }, photoRecord.id);
  assert.equal(preserved.photos.returned.length, 1);
  const nextHandover = await call('asset_issues', { ...issue, issue_date: '2026-11-04', photos: preserved.photos });
  assert.deepEqual(nextHandover.photos, {});
  assert.equal((await call('asset_issues')).find(item => item.id === preserved.id).photos.returned.length, 1);
  const deletion = (id, method = 'GET', body = {}, company = 'a') => deleteAssetList({ db, env: { HRMS_DOCUMENTS: bucket }, actor: { role: 'company_admin', company_id: company }, id, method, body });
  const disposable = await call('asset_lists', { title: 'Delete test', types: ['Chair'] });
  const disposableAsset = await call('assets', { ...asset, title: 'Delete chair', serial_number: 'DELETE-CHAIR', list_id: disposable.id, category: 'Other', custom_type: 'Chair' });
  await call('asset_issues', { ...issue, asset_id: disposableAsset.id });
  const preview = await deletion(disposable.id);
  assert.equal(preview.products.length, 1);
  assert.equal(preview.issues, 1);
  await reject(deletion(disposable.id, 'POST', { name: 'wrong', token: preview.token }), 400);
  await reject(deletion(disposable.id, 'GET', {}, 'b'), 404);
  await call('assets', { ...disposableAsset, notes: 'Changed since preview' }, disposableAsset.id);
  await reject(deletion(disposable.id, 'POST', { name: preview.title, token: preview.token }), 409);
  const freshPreview = await deletion(disposable.id);
  assert.equal((await deletion(disposable.id, 'POST', { name: freshPreview.title, token: freshPreview.token })).deleted, true);
  assert.equal((await call('assets')).some(item => item.id === disposableAsset.id), false);
  assert.equal((await call('asset_issues')).some(item => item.asset_id === disposableAsset.id), false);
  assert.equal((await call('assets')).some(item => item.id === savedAsset.id), true);
  const emptyList = await call('asset_lists', { title: 'Empty deletion', types: ['Desk'] });
  const emptyPreview = await deletion(emptyList.id);
  assert.equal((await deletion(emptyList.id, 'POST', { name: emptyPreview.title, token: emptyPreview.token })).deleted, true);
  const course = await call('courses', { title: 'Security essentials', hours: 2, status: 'Published', url: 'https://example.com' });
  await reject(call('courses', { title: 'Bad link', status: 'Published', url: 'javascript:alert(1)' }), 400);
  const enrollment = { title: 'Security training', course_id: course.id, employee_id: 'employee-a', due_date: '2026-12-01', progress: 0, status: 'Not started' };
  const assignedCourse = await call('enrollments', enrollment);
  await reject(call('enrollments', enrollment), 409);
  await reject(call('enrollments', { ...assignedCourse, status: 'Completed' }, assignedCourse.id), 400);
  await call('enrollments', { ...assignedCourse, progress: 100, status: 'Completed' }, assignedCourse.id);
  assert.deepEqual(routePages('/api/v1/talent/jobs', 'POST'), ['recruitment']);
  assert.deepEqual(routePages('/api/v1/talent/assets', 'GET'), ['assets', 'reports']);
  assert.deepEqual(parsePages(['onboarding', 'offboarding', 'learning']), ['onboarding', 'offboarding', 'learning']);
  sqlite.prepare('INSERT INTO talent_records(company_id,collection,id,payload,created_at,updated_at) VALUES(?,?,?,?,?,?)').run('a', 'assets', 'legacy-asset', JSON.stringify({ title: 'Legacy laptop', serial_number: 'LEGACY', employee_id: 'employee-a', issue_date: '2026-09-01', status: 'Assigned', purchase_price: 50000 }), '2026-09-01', '2026-09-01');
  const migration = readFileSync(new URL('../migrations/hrms/0010_asset_issues.sql', import.meta.url), 'utf8');
  sqlite.exec(migration); sqlite.exec(migration);
  const legacyAsset = (await call('assets')).find(item => item.id === 'legacy-asset');
  assert.equal(legacyAsset.purchase_price, 50000);
  assert.equal(legacyAsset.status, 'Available');
  assert.equal(legacyAsset.employee_id, undefined);
  const migratedIssues = (await call('asset_issues')).filter(item => item.asset_id === 'legacy-asset');
  assert.equal(migratedIssues.length, 1);
  assert.equal(migratedIssues[0].employee_id, 'employee-a');
  assert.equal(migratedIssues[0].issue_date, '2026-09-01');
  console.log('Talent tests passed: every module, company ownership, role checks, references, validation, duplicate prevention, revisions, checklist completion, asset returns, goals and learning completion.');
} finally { sqlite.close(); }
